name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

env:
  JAVA_VERSION: 11

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Gradle
        run: ./gradlew checkstyleMain checkstyleTest spotbugsMain spotbugsTest pmdMain pmdTest :aggregateJavadoc --stacktrace --no-daemon

      - name: Annotate Checkstyle Issues
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/build/reports/checkstyle/*.xml'

      - name: Annotate SpotBugs Issues
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/build/reports/spotbugs/*.xml'

      - name: Annotate PMD Issues
        uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: '**/build/reports/pmd/*.xml'

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --stacktrace --no-daemon

  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble --stacktrace --no-daemon

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v2

      - name: Checkout maven repo
        run: git clone https://github.com/${{ format('{0}/maven', github.repository_owner) }}.git /tmp/repo

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew publishNebulaPublicationToLocalRepoRepository --stacktrace --no-daemon

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          repository-name: ${{ format('{0}/maven', github.repository_owner) }}
          branch: main # The branch the action should deploy to.
          folder: /tmp/repo # The folder the action should deploy.
          clean: false

          token: ${{ secrets.GH_PAT_PACKAGES }}
          # https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/git.ts#L3-L8
          commit-message: Publish ${{ github.reposetory }}
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
