name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: temurin

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Gradle
        run: ./gradlew checkstyleMain checkstyleTest --stacktrace --no-daemon

      #- name: Annotate Checkstyle Issues
      #  uses: jwgmeligmeyling/checkstyle-github-action@master
      #  with:
      #    path: '**/build/reports/checkstyle/*.xml'

  lint-javadoc:
    if: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Gradle
        run: ./gradlew :aggregateJavadoc --stacktrace --no-daemon

  nohttp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: NoHttp with Gradle
        run: ./gradlew nohttp --stacktrace --no-daemon

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 21 ]
        java-distro: [ temurin ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distro }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --stacktrace --no-daemon

  build:
    needs: [ lint, nohttp, test ] # lint-javadoc,
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew jar --stacktrace --no-daemon

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout maven repo
        uses: actions/checkout@v4
        with:
          repository: marcel-repos/mvn
          path: ./mvn-repo

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew publishNebulaPublicationToLocalRepoRepository --stacktrace --no-daemon

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: marcel-repos/mvn
          branch: main # The branch the action should deploy to.
          folder: ./mvn-repo # The folder the action should deploy.
          clean: false

          token: ${{ secrets.GH_PAT_PACKAGES }}
          # https://github.com/crazy-max/ghaction-github-pages/blob/dev/src/git.ts#L3-L8
          commit-message: Publish ${{ github.repository }}
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
